{
 "title": "Plone",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "buildout",
    "query": "label_values(process_cpu_percentage, buildout)"
   }
  ]
 },
 "panels": [
  {
   "title": "7 days budget",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(process_resident_memory_bytes{buildout=\"$buildout\"}[7d]))",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(avg_over_time(process_cpu_percentage{buildout=\"$buildout\"}[7d])) / 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(disk_usage{buildout=\"$buildout\"})",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{buildout=\"$buildout\"})",
     "legendFormat": "Resident"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{buildout=\"$buildout\"})",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_percentage{buildout=\"$buildout\"})"
    }
   ]
  },
  {
   "title": "IO ops/s",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_io_read_count{buildout=\"$buildout\"}[1m]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(process_io_write_count{buildout=\"$buildout\"}[1m]))",
     "legendFormat": "writes"
    },
    {
     "expr": "sum(rate(process_io_write_bytes{buildout=\"$buildout\"}[1m]))",
     "legendFormat": "written bytes"
    },
    {
     "expr": "sum(rate(process_io_read_bytes{buildout=\"$buildout\"}[1m]))",
     "legendFormat": "read bytes"
    }
   ]
  },
  {
   "title": "RSS Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{buildout=\"$buildout\"}) by (process)",
     "legendFormat": "{{process}}"
    },
    {
     "expr": "sum(avg_over_time(process_resident_memory_bytes{buildout=\"$buildout\"}[7d]))",
     "legendFormat": "total memory average over 7 days"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(disk_usage{buildout=\"$buildout\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (process) (process_cpu_percentage{buildout=\"$buildout\"})    ",
     "legendFormat": "{{process}}"
    },
    {
     "expr": "sum(avg_over_time(process_cpu_percentage{buildout=\"$buildout\"}[7d]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (process) (process_open_fds{buildout=\"$buildout\"})",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "IO ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_io_read_count{buildout=\"$buildout\"}[$__interval])",
     "legendFormat": "{{process}} read"
    },
    {
     "expr": "rate(process_io_write_count{buildout=\"$buildout\"}[$__interval])",
     "legendFormat": "{{process}} write"
    }
   ]
  },
  {
   "title": "IO bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_io_read_bytes{buildout=\"$buildout\"}[$__interval])",
     "legendFormat": "{{process}} read"
    },
    {
     "expr": "rate(process_io_write_bytes{buildout=\"$buildout\"}[$__interval])",
     "legendFormat": "{{process}} write"
    }
   ]
  }
 ]
}