global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "node_rules.yaml"
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
#  - job_name: app
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['host.docker.internal:10088']
  - job_name: pushgateway
    honor_labels: true
    scrape_interval: 5s
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['172.21.0.1:9100']
      - targets: ['172.21.0.1:9101']
#      - targets: ['host.docker.internal:9100']
